// <auto-generated />
using System;
using HealthyBreakfastApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthyBreakfastApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313120534_AddIsDeletedAndPendingChanges")]
    partial class AddIsDeletedAndPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fiber")
                        .HasColumnType("numeric");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Protein")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IngredientId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.IngredientCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CategoryId");

                    b.ToTable("IngredientCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Oats",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Seeds",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Fruits",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Milk",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Sweetener",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealId"));

                    b.Property<int?>("ApproxCalories")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ApproxCarbs")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("ApproxFats")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("ApproxProtein")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MealId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            MealId = 1,
                            BasePrice = 40m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional overnight oats base",
                            IsComplete = true,
                            IsDeleted = false,
                            MealName = "Classic Overnight Oats",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MealId = 2,
                            BasePrice = 50m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build your perfect breakfast",
                            IsComplete = true,
                            IsDeleted = false,
                            MealName = "Custom Breakfast Bowl",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MealId = 3,
                            BasePrice = 60m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High protein breakfast option",
                            IsComplete = true,
                            IsDeleted = false,
                            MealName = "Protein Power Bowl",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.MealOption", b =>
                {
                    b.Property<int>("MealOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealOptionId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSelectable")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MealOptionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MealId");

                    b.ToTable("MealOptions");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.MealOptionIngredient", b =>
                {
                    b.Property<int>("MealOptionIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealOptionIngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("MealOptionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MealOptionIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealOptionId");

                    b.ToTable("MealOptionIngredients");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryAddressId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserMealId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("OrderStatus")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("ScheduledFor")
                        .HasDatabaseName("IX_Orders_ScheduledFor");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.HasIndex("UserMealId");

                    b.HasIndex("UserId", "OrderStatus")
                        .HasDatabaseName("IX_Orders_UserId_Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserMealId")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserMealId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.ScheduledOrder", b =>
                {
                    b.Property<int>("ScheduledOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduledOrderId"));

                    b.Property<Guid>("AuthId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanModify")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfirmedOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryTimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProcessedToOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("MealId")
                        .HasColumnType("integer");

                    b.Property<string>("MealImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NutritionalSummary")
                        .HasColumnType("text");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("date");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ScheduledOrderId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("ScheduledFor")
                        .HasDatabaseName("IX_ScheduledOrders_ScheduledFor");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.HasIndex("AuthId", "ScheduledFor")
                        .HasDatabaseName("IX_ScheduledOrders_AuthId_ScheduledFor");

                    b.HasIndex("ScheduledFor", "OrderStatus")
                        .HasDatabaseName("IX_ScheduledOrders_ScheduledFor_OrderStatus");

                    b.ToTable("ScheduledOrders");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.ScheduledOrderIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduledOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ScheduledOrderId")
                        .HasDatabaseName("IX_ScheduledOrderIngredients_ScheduledOrderId");

                    b.ToTable("ScheduledOrderIngredients");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.ServiceableLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTimeSlot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LandmarkOrSociety")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Pincode");

                    b.HasIndex("City", "Area");

                    b.ToTable("ServiceableLocations");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryAddressId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("NextScheduledDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserMealId")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Subscriptions_UserId");

                    b.HasIndex("UserMealId");

                    b.HasIndex("UserId", "UserMealId")
                        .HasDatabaseName("IX_Subscriptions_UserId_UserMealId");

                    b.HasIndex("Active", "StartDate", "EndDate")
                        .HasDatabaseName("IX_Subscriptions_Active_StartDate_EndDate");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.SubscriptionSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasComment("Day of week: 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Number of items to deliver on this day");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleId");

                    b.HasIndex("SubscriptionId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("IX_SubscriptionSchedules_Subscription_DayOfWeek");

                    b.ToTable("SubscriptionSchedules", t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionSchedules_DayOfWeek", "\"DayOfWeek\" >= 0 AND \"DayOfWeek\" <= 6");

                            t.HasCheckConstraint("CK_SubscriptionSchedules_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WalletBalance")
                        .IsConcurrencyToken()
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "testuser@healthybreakfast.com",
                            Name = "TestUser",
                            Phone = "1234567890",
                            Role = "User",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WalletBalance = 625m
                        });
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Block")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Floor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ServiceableLocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Wing")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceableLocationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("IX_UserAddresses_Primary_Unique")
                        .HasFilter("\"IsPrimary\" = true AND \"IsActive\" = true");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserAuthMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mapping_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MappingId"));

                    b.Property<Guid>("AuthId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("MappingId");

                    b.HasIndex("AuthId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_auth_mapping", (string)null);
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserMeal", b =>
                {
                    b.Property<int>("UserMealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserMealId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserMealId");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMeals");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserMealIngredient", b =>
                {
                    b.Property<int>("UserMealIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserMealIngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserMealId")
                        .HasColumnType("integer");

                    b.HasKey("UserMealIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserMealId");

                    b.ToTable("UserMealIngredients");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("WalletTransactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 625m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial wallet balance",
                            Type = "Credit",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.IngredientCategory", "IngredientCategory")
                        .WithMany("Ingredients")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientCategory");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.MealOption", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.IngredientCategory", "IngredientCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Meal", "Meal")
                        .WithMany("MealOptions")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientCategory");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.MealOptionIngredient", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.MealOption", "MealOption")
                        .WithMany("MealOptionIngredients")
                        .HasForeignKey("MealOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MealOption");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Order", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.UserAddress", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.UserMeal", "UserMeal")
                        .WithMany()
                        .HasForeignKey("UserMealId");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("User");

                    b.Navigation("UserMeal");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.UserMeal", "UserMeal")
                        .WithMany()
                        .HasForeignKey("UserMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("UserMeal");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.ScheduledOrder", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.UserAddress", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.ScheduledOrderIngredient", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.ScheduledOrder", "ScheduledOrder")
                        .WithMany("Ingredients")
                        .HasForeignKey("ScheduledOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ScheduledOrder");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.UserAddress", "DeliveryAddress")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.UserMeal", "UserMeal")
                        .WithMany()
                        .HasForeignKey("UserMealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryAddress");

                    b.Navigation("User");

                    b.Navigation("UserMeal");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.SubscriptionSchedule", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Subscription", "Subscription")
                        .WithMany("WeeklySchedule")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.ServiceableLocation", "ServiceableLocation")
                        .WithMany("UserAddresses")
                        .HasForeignKey("ServiceableLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceableLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserAuthMapping", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.User", "User")
                        .WithOne("AuthMapping")
                        .HasForeignKey("HealthyBreakfastApp.Domain.Entities.UserAuthMapping", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserMeal", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserMealIngredient", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthyBreakfastApp.Domain.Entities.UserMeal", "UserMeal")
                        .WithMany("UserMealIngredients")
                        .HasForeignKey("UserMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("UserMeal");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("HealthyBreakfastApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.IngredientCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Meal", b =>
                {
                    b.Navigation("MealOptions");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.MealOption", b =>
                {
                    b.Navigation("MealOptionIngredients");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.ScheduledOrder", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.ServiceableLocation", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AuthMapping");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserAddress", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("HealthyBreakfastApp.Domain.Entities.UserMeal", b =>
                {
                    b.Navigation("UserMealIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
